"""스키마 v1 — spec §9 의 19개 테이블 (P0-4-5).

`candles` 는 여기 없다. 파티션 부모라서 autogenerate 대상에서 제외되며 0002 가
수기 DDL 로 만든다 (plan P-8). 나머지 19개 + candles = §9 의 20개다.

Revision ID: 0001
Revises:
Create Date: 2026-08-03
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Text(), nullable=False),
        sa.Column("module", sa.Text(), nullable=False),
        sa.Column(
            "level",
            sa.Enum(
                "debug", "info", "warning", "error", "critical", name="level", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "ts", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_logs")),
    )
    op.create_index(op.f("ix_event_logs_event_type"), "event_logs", ["event_type"], unique=False)
    op.create_index(op.f("ix_event_logs_trace_id"), "event_logs", ["trace_id"], unique=False)
    op.create_index(op.f("ix_event_logs_ts"), "event_logs", ["ts"], unique=False)
    op.create_table(
        "instruments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "market",
            sa.Enum("KRX", "NASDAQ", "NYSE", "UPBIT", name="market", native_enum=False),
            nullable=False,
        ),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "asset_type",
            sa.Enum("stock", "coin", name="asset_type", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "currency", sa.Enum("KRW", "USD", name="currency", native_enum=False), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instruments")),
        sa.UniqueConstraint("market", "symbol", name="market_symbol"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("google_sub", sa.Text(), nullable=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("admin", "member", "trial", name="role", native_enum=False),
            nullable=False,
        ),
        sa.Column("trial_expires_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("google_sub", name=op.f("uq_users_google_sub")),
    )
    op.create_table(
        "account_balances",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("broker", sa.Text(), nullable=False),
        sa.Column(
            "currency", sa.Enum("KRW", "USD", name="currency", native_enum=False), nullable=False
        ),
        sa.Column("cash", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("positions_value", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("fx_rate_snapshot", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column(
            "fetched_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_account_balances_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account_balances")),
    )
    op.create_index(
        "ix_account_balances_user_fetched",
        "account_balances",
        ["user_id", "fetched_at"],
        unique=False,
    )
    op.create_table(
        "allocation_ledger",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "ts", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "bucket",
            sa.Enum("scalp", "swing", "longterm", name="bucket", native_enum=False),
            nullable=False,
        ),
        sa.Column("delta_amount", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "trade",
                "transition",
                "rebalance",
                "deposit",
                "withdraw",
                name="reason",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("ref_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_allocation_ledger_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocation_ledger")),
    )
    op.create_index(
        "ix_allocation_ledger_user_ts", "allocation_ledger", ["user_id", "ts"], unique=False
    )
    op.create_table(
        "analysis_reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Text(), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.Enum("tech", "fund", name="type", native_enum=False), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_analysis_reports_instrument_id_instruments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_reports")),
    )
    op.create_index(
        op.f("ix_analysis_reports_trace_id"), "analysis_reports", ["trace_id"], unique=False
    )
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("config_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("report_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_backtest_runs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_runs")),
    )
    op.create_table(
        "broker_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("broker", sa.Text(), nullable=False),
        sa.Column("encrypted_ref", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_broker_credentials_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_credentials")),
        sa.UniqueConstraint("user_id", "broker", name="user_broker"),
    )
    op.create_table(
        "candle_quality_issues",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "timeframe",
            sa.Enum("5m", "15m", "1h", "4h", "1d", name="timeframe", native_enum=False),
            nullable=False,
        ),
        sa.Column("ts_start", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("ts_end", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "issue_type",
            sa.Enum(
                "ohlc_violation",
                "missing_bars",
                "price_spike",
                "volume_spike",
                "non_positive_price",
                "negative_volume",
                name="issue_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("detail_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "resolved", "ignored", name="status", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "detected_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_candle_quality_issues_instrument_id_instruments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candle_quality_issues")),
    )
    op.create_index(
        "ix_candle_quality_issues_open_range",
        "candle_quality_issues",
        ["instrument_id", "timeframe", "ts_start", "ts_end"],
        unique=False,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "sent", "failed", name="status", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "ts", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_notifications_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_table(
        "portfolio_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "ts", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("total_krw", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("fx_pnl", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("by_bucket_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("by_account_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_portfolio_snapshots_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_portfolio_snapshots")),
    )
    op.create_index(
        "ix_portfolio_snapshots_user_ts", "portfolio_snapshots", ["user_id", "ts"], unique=False
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "bucket",
            sa.Enum("scalp", "swing", "longterm", name="bucket", native_enum=False),
            nullable=False,
        ),
        sa.Column("qty", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("avg_entry", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("stop_loss", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("take_profit", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column(
            "status",
            sa.Enum("open", "closed", "transitioned", name="status", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "opened_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("pnl", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_positions_instrument_id_instruments"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_positions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_positions")),
    )
    op.create_index(
        "ix_positions_open",
        "positions",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "risk_policies",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "bucket",
            sa.Enum("scalp", "swing", "longterm", name="bucket", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "preset",
            sa.Enum("conservative", "standard", "aggressive", name="preset", native_enum=False),
            nullable=False,
        ),
        sa.Column("risk_pct", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("min_rr", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("daily_loss_limit_pct", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("max_positions", sa.Integer(), nullable=False),
        sa.Column("trailing_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_risk_policies_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "bucket", name=op.f("pk_risk_policies")),
    )
    op.create_table(
        "structures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "timeframe",
            sa.Enum("5m", "15m", "1h", "4h", "1d", name="timeframe", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum(
                "order_block",
                "fvg",
                "ifvg",
                "trendline",
                "channel",
                "pattern",
                name="type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("range_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "invalidated", "flipped", name="status", native_enum=False),
            nullable=False,
        ),
        sa.Column("rule_version", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("invalidated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_structures_instrument_id_instruments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_structures")),
    )
    op.create_index(
        "ix_structures_active",
        "structures",
        ["instrument_id", "timeframe"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "trade_proposals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.Text(), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "bucket",
            sa.Enum("scalp", "swing", "longterm", name="bucket", native_enum=False),
            nullable=False,
        ),
        sa.Column("side", sa.Enum("buy", "sell", name="side", native_enum=False), nullable=False),
        sa.Column("entry", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("stop_loss", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("take_profit", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("rr", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("score", sa.Double(), nullable=False),
        sa.Column("evidence_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_summary", sa.Text(), nullable=True),
        sa.Column("valid_until", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", "expired", name="status", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instruments.id"],
            name=op.f("fk_trade_proposals_instrument_id_instruments"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_proposals")),
    )
    op.create_index(
        op.f("ix_trade_proposals_trace_id"), "trade_proposals", ["trace_id"], unique=False
    )
    op.create_table(
        "approved_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("total_qty", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("entry_plan_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stop_loss", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("tp_ladder_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stop_policy_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policy_snapshot_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("idempotency_root", sa.Text(), nullable=False),
        sa.Column("valid_until", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "approved", "rejected", "expired", name="status", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["trade_proposals.id"],
            name=op.f("fk_approved_orders_proposal_id_trade_proposals"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_approved_orders_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approved_orders")),
        sa.UniqueConstraint("idempotency_root", name=op.f("uq_approved_orders_idempotency_root")),
    )
    op.create_table(
        "transitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_bucket",
            sa.Enum("scalp", "swing", "longterm", name="from_bucket", native_enum=False),
            nullable=False,
        ),
        sa.Column(
            "to_bucket",
            sa.Enum("scalp", "swing", "longterm", name="to_bucket", native_enum=False),
            nullable=False,
        ),
        sa.Column("decision_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "ts", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["position_id"], ["positions.id"], name=op.f("fk_transitions_position_id_positions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transitions")),
    )
    op.create_table(
        "risk_plan_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("approved_order_id", sa.Uuid(), nullable=False),
        sa.Column("position_id", sa.Uuid(), nullable=True),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column(
            "trigger",
            sa.Enum(
                "first_tp_filled",
                "trailing",
                "time_stop",
                "gap_open",
                "transition",
                "manual",
                name="trigger",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("stop_loss", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("tp_ladder_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reason_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("trace_id", sa.Text(), nullable=False),
        sa.Column(
            "decided_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_order_id"],
            ["approved_orders.id"],
            name=op.f("fk_risk_plan_revisions_approved_order_id_approved_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
            name=op.f("fk_risk_plan_revisions_position_id_positions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_plan_revisions")),
        sa.UniqueConstraint("approved_order_id", "revision_no", name="approved_order_revision"),
    )
    op.create_index(
        op.f("ix_risk_plan_revisions_trace_id"), "risk_plan_revisions", ["trace_id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("approved_order_id", sa.Uuid(), nullable=False),
        sa.Column("position_id", sa.Uuid(), nullable=True),
        sa.Column("revision_id", sa.Uuid(), nullable=True),
        sa.Column(
            "order_kind",
            sa.Enum(
                "entry", "take_profit", "stop_loss", "close", name="order_kind", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("leg_index", sa.Integer(), nullable=False),
        sa.Column("requested_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column("requested_qty", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("broker_order_id", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "watching",
                "submitted",
                "partially_filled",
                "filled",
                "expired",
                "cancelled",
                "failed",
                name="status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("filled_qty", sa.Numeric(precision=38, scale=18), nullable=False),
        sa.Column("avg_price", sa.Numeric(precision=38, scale=18), nullable=True),
        sa.Column(
            "ts", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["approved_order_id"],
            ["approved_orders.id"],
            name=op.f("fk_orders_approved_order_id_approved_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["position_id"], ["positions.id"], name=op.f("fk_orders_position_id_positions")
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["risk_plan_revisions.id"],
            name=op.f("fk_orders_revision_id_risk_plan_revisions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_orders_idempotency_key")),
    )
    op.create_index(op.f("ix_orders_broker_order_id"), "orders", ["broker_order_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_broker_order_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_risk_plan_revisions_trace_id"), table_name="risk_plan_revisions")
    op.drop_table("risk_plan_revisions")
    op.drop_table("transitions")
    op.drop_table("approved_orders")
    op.drop_index(op.f("ix_trade_proposals_trace_id"), table_name="trade_proposals")
    op.drop_table("trade_proposals")
    op.drop_index(
        "ix_structures_active",
        table_name="structures",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("structures")
    op.drop_table("risk_policies")
    op.drop_index(
        "ix_positions_open", table_name="positions", postgresql_where=sa.text("status = 'open'")
    )
    op.drop_table("positions")
    op.drop_index("ix_portfolio_snapshots_user_ts", table_name="portfolio_snapshots")
    op.drop_table("portfolio_snapshots")
    op.drop_table("notifications")
    op.drop_index(
        "ix_candle_quality_issues_open_range",
        table_name="candle_quality_issues",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_table("candle_quality_issues")
    op.drop_table("broker_credentials")
    op.drop_table("backtest_runs")
    op.drop_index(op.f("ix_analysis_reports_trace_id"), table_name="analysis_reports")
    op.drop_table("analysis_reports")
    op.drop_index("ix_allocation_ledger_user_ts", table_name="allocation_ledger")
    op.drop_table("allocation_ledger")
    op.drop_index("ix_account_balances_user_fetched", table_name="account_balances")
    op.drop_table("account_balances")
    op.drop_table("users")
    op.drop_table("instruments")
    op.drop_index(op.f("ix_event_logs_ts"), table_name="event_logs")
    op.drop_index(op.f("ix_event_logs_trace_id"), table_name="event_logs")
    op.drop_index(op.f("ix_event_logs_event_type"), table_name="event_logs")
    op.drop_table("event_logs")
    # ### end Alembic commands ###
